# Generated by Django 5.0.3 on 2024-04-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirts',
            name='gender',
        ),
    ]
