# Generated by Django 5.0.3 on 2024-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0002_remove_tshirts_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentsname2', models.CharField(max_length=25)),
                ('membersname2', models.CharField(max_length=25)),
                ('color2', models.CharField(max_length=25)),
                ('size2', models.CharField(max_length=25)),
                ('units2', models.IntegerField()),
            ],
        ),
    ]
