# Generated by Django 5.0.3 on 2024-04-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0003_hoodies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentsname3', models.CharField(max_length=25)),
                ('membersname3', models.CharField(max_length=25)),
                ('item', models.CharField(max_length=25)),
                ('units3', models.IntegerField()),
            ],
        ),
    ]
