# Generated by Django 5.0.3 on 2024-04-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0004_goodies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentsname', models.CharField(max_length=25)),
                ('membersname', models.CharField(max_length=25)),
                ('adm', models.CharField(max_length=25)),
                ('Class', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=25)),
            ],
        ),
    ]
